author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /corinth
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://images.readux.ecds.emory.edu:8443/cantaloupe/iiif/2/skqjb_00000001.jpg/full/full/0/default.jpg
image_size:
  page:
    height: 2700
    width: 4200
permalink: pretty
publication_info:
  date: '2021'
  editors: []
  title: Andreae Alciati emblematvm libellvs.
show_annotation_author: true
source_info:
  title: Andreae Alciati emblematvm libellvs.
  via_readux: true
tagline: an annotated digital edition
title: Andreae Alciati emblematvm libellvs.
url: https://jpkarlsberg.github.io
version: 0.7
